services:
  ros-noetic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros-noetic-silvus
    image: ros-noetic-silvus
    user: user
    privileged: true
    environment:
      - DISPLAY
      - ROS_MASTER_URI
      - ROS_IP
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../ws:/home/user/ws
    network_mode: host
    ipc: host
    command: ["bash"]
